/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject1;

public class App {
    public static void main(String[] args) {
      App aplicacao = new App ();
      pessoa p1 = new pessoa ("neguin da zl");
      automovel aal = new automovel ("carro");
      piloto cc1 = new piloto ("luffy");
      carro crr1 = new carro ("bmw");
    }}

